capture_zones:
  time_zone_id: "Eastern Standard Time"
  scoring_start: "13:45"
  scoring_end: "13:58"

  ring_effect_id: 130
  ring_refresh_interval_seconds: 2

  boundary:
    enabled: false
    effect_count: 20
    height_offset: 0.1

  zones:
    - name: "Configure"
      x: 283
      y: 0
      z: -536
      radius: 10.0
      weight: 2



pvp_schedule:
  enabled_start: "21:00"
  enabled_end: "23:59"